### ISSUE TITLE
Disable CPF when doing a deploy or redeploy task

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/ml-gradle#233]
I **don`t** want to  install cpf for a given configuration, based on the environment. The way I did this in my gradle file is, I check the environment for which the gradle task is being run and for one particular environment I remove the CPF commands
 ```
mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployCpfConfigsCommand"))
 mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployDomainsCommand"))
 mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployPipelinesCommand"))
```
But I get the following exception when I do the  `mlDeploy`.. If this is not the right way to do it, what can be done, so I don;t need to deploy `CPF`, `Domains` and `Pipelines` for a given environment.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> 404 Not Found

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':mlDeployApp'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.springframework.web.client.HttpClientErrorException: 404 Not Found
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at com.marklogic.rest.util.MgmtResponseErrorHandler.handleError(MgmtResponseErrorHandler.java:19)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:465)
	at com.marklogic.mgmt.ManageClient.postXml(ManageClient.java:92)
	at com.marklogic.mgmt.AbstractManager.postPayload(AbstractManager.java:59)
	at com.marklogic.mgmt.AbstractResourceManager.save(AbstractResourceManager.java:81)
	at com.marklogic.appdeployer.command.AbstractCommand.saveResource(AbstractCommand.java:99)
	at com.marklogic.appdeployer.command.AbstractResourceCommand.execute(AbstractResourceCommand.java:35)
	at com.marklogic.appdeployer.impl.AbstractAppDeployer.deploy(AbstractAppDeployer.java:58)
	at com.marklogic.appdeployer.AppDeployer$deploy.call(Unknown Source)
	at com.marklogic.gradle.task.DeployAppTask.deployApp(DeployAppTask.groovy:9)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 69 more


```

**Comment by rjrudin** [comment]
Can you run "mlDeploy -i" and show the last several lines of logging before the error occurs? I'm looking for what command is run that causes the 404. I'm guessing it's something that expects e.g. a CPF domain to exist (like deploying flexrep). 

That approach will work for removing commands - you can also do what's shown at https://github.com/marklogic-community/ml-gradle/wiki/Ignoring-commands , although that only works for mlDeploy.

**Comment by ravi-b-m** [comment]
Yeah I do have flexrep configured..  Does Flexrep needs CPF enabled ? as I use this as flexprep target (replica) server and I do push from master to this server. 

```
Executing command [com.marklogic.appdeployer.command.flexrep.DeployConfigsCommand] with sort order [1000]
Processing files in directory: D:\work\content-repository\src\main\ml-config\flexrep\configs
Processing file: D:\work\content-repository\src\main\ml-config\flexrep\configs\flexrep-config.xml
Sending XML GET request as user 'content-repo-manager' to path: /manage/v2/databases/content-repo-content/flexrep/configs
Creating config: documents
Sending XML POST request as user 'content-repo-manager' to path: /manage/v2/databases/content-repo-content/flexrep/configs
POST request for "http://10.239.12.161:8002/manage/v2/databases/content-repo-content/flexrep/configs" resulted in 404 (Not Found); invoking error handler

```

**Comment by ravi-b-m** [comment]
I think I fixed it by removing flexrep commands too 
 mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployCpfConfigsCommand"))
        mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployDomainsCommand"))
        ```
mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployPipelinesCommand"))
        mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployConfigsCommand"))
        mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployFlexrepCommand"))
        mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand("DeployTargetsCommand"))
```
Since this is a target Flexrep server and it does not require flexrep on it, so I removed these commands as well. 
Is this right or will this cause any unforeseen error that I missed ?

**Comment by rjrudin** [comment]
That sounds like what you want. A Flexrep config references a CPF domain. If that domain is missing, the Management API will throw an error, that's the 404 you're getting. 

You can simplify the Groovy code a bit too, something like this (haven't verified the syntax:

    for (name in ["DeployCpfConfigsCommand", "DeployDomainsCommand", etc..]) {
      mlAppDeployer.getCommands().remove(mlAppDeployer.getCommand(name)
    }
