### ISSUE TITLE
Loading REST service extensions via ml-gradle to V9.0-3

### ISSUE THREAD

**Issue by ravi-b-m** [marklogic-community/ml-gradle#253]
Marklogic v9.0-3
ml-gradle v2.9.0

I recently upgraded my marklogic from v8.0-5.3 to v9.0-3.. And when I load my service extensions I am getting the following error .. This works in v8.0-5.3
```
Import module namespace http://marklogic.com/rest-api/endpoints/config does not match target namespace http://marklogic.com/rest-api/endpoints/config_DELETE_IF_UNUSED of imported module /MarkLogic/rest-api/endpoints/config.xqy;
```
Not sure what this error means ? Following is the the full trace of the error.. Any suggestion as to what is going wrong here ?

```java
:mlReloadModules (Thread[Daemon worker,5,main]) completed. Took 0.003 secs.
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "ThreadPoolTaskExecutor-5" com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Bad Request. Server Message: RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: invalid crSearch extension: could not parse XQuery extension crSearch; please see the server error log for detail XDMP-IMPMODNS: (err:XQST0059) Import module namespace http://marklogic.com/rest-api/endpoints/config does not match target namespace http://marklogic.com/rest-api/endpoints/config_DELETE_IF_UNUSED of imported module /MarkLogic/rest-api/endpoints/config.xqy; crSearch either is not a valid module or does not provide extension functions (delete, get, put, post) in the http://marklogic.com/rest-api/resource/crSearch namespace
	at com.marklogic.client.impl.JerseyServices.putPostValueImpl(JerseyServices.java:3014)

	at com.marklogic.client.impl.JerseyServices.putValue(JerseyServices.java:2877)
	at com.marklogic.client.impl.ResourceExtensionsImpl.writeServices(ResourceExtensionsImpl.java:206)
	at com.marklogic.client.modulesloader.impl.DefaultModulesLoader$1.run(DefaultModulesLoader.java:451)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
```

**Comment by ravi-b-m** [comment]
I think I figured out my issue and I resolved it.. in my Xquery rest extension I was referring to some internal ML stuff, which I was not using but never deleted the imports, which caused the error.. Once I removed everything worked.. Following is the import I removed and it worked, if anyone is interested..

```xquery
import module namespace conf = "http://marklogic.com/rest-api/endpoints/config" at "/MarkLogic/rest-api/endpoints/config.xqy";
import module namespace logger = "http://marklogic.com/rest-api/logger" at "/MarkLogic/rest-api/lib/logger.xqy";
import module namespace config-query = "http://marklogic.com/rest-api/models/config-query" at "/MarkLogic/rest-api/models/config-query-model.xqy";
import module namespace dbut = "http://marklogic.com/rest-api/lib/db-util" at "/MarkLogic/rest-api/lib/db-util.xqy";

```
