### ISSUE TITLE
Mutual SSL handshake failure

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic-community/ml-gradle#271]
I am following the instructions for using mutual SSL but I am getting an SSL Handshake error. When I turn off client cert verification it works.

```
Unable to clear database; cause: I/O error on POST request for "https://localhost:8002/manage/v2/databases/sslProject-modules": Received fatal alert: handshake_failure; nested exception is javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
Exception in thread "ThreadPoolTaskExecutor-1" com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:184)
	at com.marklogic.client.impl.DigestChallengeFilter.handle(DigestChallengeFilter.java:34)
	at com.sun.jersey.api.client.filter.HTTPDigestAuthFilter.handle(HTTPDigestAuthFilter.java:493)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:680)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:568)
	at com.marklogic.client.impl.JerseyServices.doPost(JerseyServices.java:3999)
	at com.marklogic.client.impl.JerseyServices.postResource(JerseyServices.java:3275)
	at com.marklogic.client.impl.JerseyServices.postBulkDocuments(JerseyServices.java:3395)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:613)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:605)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:589)
	at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
	at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:78)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2033)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1779)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1130)
	at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1216)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1128)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:535)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:403)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:115)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:170)
	... 19 more
```

My build.gradle is:
```
apply plugin: "com.marklogic.ml-gradle"

ext {
    def mlManageConfig = mlManageClient.getManageConfig()

    // get the ssl context
    def context = new com.example.MLGradleContext()
    def hostnameVerifier = com.marklogic.client.DatabaseClientFactory.SSLHostnameVerifier.Builtin.ANY

    mlManageClient.setRestTemplate(context.getRestTemplate(mlManageConfig))
    mlManageClient.setAdminRestTemplate(context.getAdminRestTemplate(mlManageConfig))

    mlAppConfig.restSslContext = context.newSslContext()
    mlAppConfig.restSslHostnameVerifier = hostnameVerifier 

    mlAppConfig.appServicesSslContext = context.newSslContext()
    mlAppConfig.appServicesSslHostnameVerifier = hostnameVerifier 

}
```
I have a jar file to create the SSL context and Rest Template:

```java
    private SSLHostnameVerifier hostnameVerifier = SSLHostnameVerifier.Builtin.ANY;
    private static final String ML_CLIENT_CERT_PASSWORD ="abc123";
    private static final String ML_CLIENT_CERT_FILE ="certificate.p12";
    private static final String ML_CLIENT_CERT_TYPE ="PKCS12";

    public MLGradleContext() {
    }

    public SSLContext newSslContext() {
        System.out.println("In getSslContext");
        System.out.println("Using certifcation "+ ML_CLIENT_CERT_FILE);
        try {
            // adding trust store
            TrustManager[] trust = new TrustManager[] { new NaiveTrustManager() };
            // adding key store
            KeyStore clientKeyStore = KeyStore.getInstance(ML_CLIENT_CERT_TYPE);
            clientKeyStore.load(getClass().getResourceAsStream(ML_CLIENT_CERT_FILE), ML_CLIENT_CERT_PASSWORD.toCharArray());
            // using SunX509 format
            KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
            keyManagerFactory.init(clientKeyStore, ML_CLIENT_CERT_PASSWORD.toCharArray());
            KeyManager[] key = keyManagerFactory.getKeyManagers();
            SSLContext sslContext = SSLContext.getInstance("TLSv1");
            sslContext.init(key, trust, null);
            return sslContext;
        } catch (Exception e) {
            System.out.println("Exception occurred building SSL Content");
            throw new RuntimeException(e);
        }

    }

    public RestTemplate getRestTemplate(ManageConfig mlManageConfig) {
        String username = mlManageConfig.getUsername();
        String password = mlManageConfig.getPassword();
        return newRestTemplate(mlManageConfig, username, password);
    }

    public RestTemplate getAdminRestTemplate(ManageConfig mlManageConfig) {
        String username = mlManageConfig.getAdminUsername();
        String password = mlManageConfig.getAdminPassword();
        return newRestTemplate(mlManageConfig, username, password);
    }

    private RestTemplate newRestTemplate(ManageConfig mlManageConfig, String username, String password) {

        SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(newSslContext(), SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
        AuthScope scope = new org.apache.http.auth.AuthScope(mlManageConfig.getHost(), mlManageConfig.getPort(), AuthScope.ANY_REALM);
        UsernamePasswordCredentials credentials = new UsernamePasswordCredentials(username, password);
        BasicCredentialsProvider provider = new BasicCredentialsProvider();
        provider.setCredentials(scope, credentials);

        CloseableHttpClient httpClient = HttpClients.custom().setDefaultCredentialsProvider(provider).setSSLSocketFactory(socketFactory).build();

        HttpComponentsClientHttpRequestFactory requestFactory = new HttpComponentsClientHttpRequestFactory(httpClient);
        return new RestTemplate(requestFactory);
    }

    private static class NaiveTrustManager implements X509TrustManager {

        @Override
        public X509Certificate[] getAcceptedIssuers() {
            return null;
        }


        public void checkClientTrusted(X509Certificate[] certs, String authType) {
        }


        public void checkServerTrusted(X509Certificate[] certs, String authType) {
        }
    }

```

**Comment by rjrudin** [comment]
Are you able to share the certificate template that you're using to configure SSL on the Manage API server?

**Comment by rjkennedy98** [comment]
[cert.zip](https://github.com/marklogic-community/ml-gradle/files/1536479/cert.zip)

**Comment by rjrudin** [comment]
I believe this is now addressed by the 2-way SSL sample project
