### ISSUE TITLE
ml-gradle web services basic authentication exceptions

### ISSUE THREAD

**Issue by tomaszs86** [marklogic-community/ml-gradle#303]
When calling mlDeploy using ml-gradle 3.0.0 application throws exception during installation custom web services located in ml-modules/services folder.

```
Writing resource services source for MY-WEBSERVICE-NAME
Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.JerseyServices.putPostValueImpl(JerseyServices.java:2831)
        at com.marklogic.client.impl.JerseyServices.putValue(JerseyServices.java:2693)
        at com.marklogic.client.impl.ResourceExtensionsImpl.writeServices(ResourceExtensionsImpl.java:206)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader$1.run(DefaultModulesLoader.java:428)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

App servers on port 8000, 8001, 8002 have basic authentication enabled, internal security enabled and SSL disabled.  My custom app server on port 8020 has this same configuration.

gradle.properties: 

```
mlAppServicesAuthentication=basic
mlAdminAuthentication=basic
mlManageAuthentication=basic
```

The module database is filled with data, but my custom web services are missing because of exceptions.

**Comment by jaklan** [comment]
+1, the same problem

**Comment by jaklan** [comment]
When using ml-gradle 3.4 with:
`mlAppServicesAuthentication=basic
mlAdminAuthentication=basic
mlManageAuthentication=basic`
there's still an error:
`Error caught while loading modules, cause: unsupported auth scheme: [Basic realm=public]
java.lang.IllegalArgumentException: unsupported auth scheme: [Basic realm=public]
        at com.burgstaller.okhttp.digest.DigestAuthenticator.findDigestHeader(DigestAuthenticator.java:198)
        at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:163)
        at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:30)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:289)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:157)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2810)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2740)
        at com.marklogic.client.impl.ResourceExtensionsImpl.writeServices(ResourceExtensionsImpl.java:206)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installService$1(DefaultModulesLoader.java:408)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

**Comment by rjrudin** [comment]
Try 

    mlRestAuthentication=basic

as REST modules have to be loaded via your custom REST server (as opposed to non-REST modules, which can be loaded via 8000).

All properties for configuring the connection to your REST server (8020) are at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#rest-api-server-connection-properties

**Comment by tomaszs86** [comment]
It works. Thanks

**Comment by darrelcox** [comment]
With :

`mlRestAuthentication=basic`

I'm getting this error during mlDeploy

```
Writing resource services source for entity
Error caught while loading modules, cause: Local message: config/resources write failed: Unauthorized. Server Message: Unauthorized
com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2873)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2740)
        at com.marklogic.client.impl.ResourceExtensionsImpl.writeServices(ResourceExtensionsImpl.java:206)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installService$1(DefaultModulesLoader.java:408)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:501)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by rjrudin** [comment]
@darrelcox Can you open a new issue with that problem? Please include the version of ml-gradle you're using too.
