### ISSUE TITLE
Roxy migration: properties.xml is not deployable

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#320]
After going through the Roxy migration steps, `rest-api/config/properties.xml` ends up at `src/main/ml-modules/options/properties.xml`. Attempting to run `gradle mlLoadModules` with it there results in an error: 

```
Error caught while loading modules, cause: Local message: /config/query write failed: Internal Server Error. Server Message: XDMP-NONMIXEDCOMPLEXCONT: fn:data(<properties xmlns="http://marklogic.com/rest-api"><content-versions>...</content-versions>...</properties>) -- Node has complex type with non-mixed complex content . See the MarkLogic server error log for further detail.
com.marklogic.client.FailedRequestException: Local message: /config/query write failed: Internal Server Error. Server Message: XDMP-NONMIXEDCOMPLEXCONT: fn:data(<properties xmlns="http://marklogic.com/rest-api"><content-versions>...</content-versions>...</properties>) -- Node has complex type with non-mixed complex content . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2873)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2730)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installQueryOptions$3(DefaultModulesLoader.java:464)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Error caught while loading modules, cause: Local message: /config/query write failed: Internal Server Error. Server Message: XDMP-NONMIXEDCOMPLEXCONT: fn:data(<properties xmlns="http://marklogic.com/rest-api"><content-versions>...</content-versions>...</properties>) -- Node has complex type with non-mixed complex content . See the MarkLogic server error log for further detail.
com.marklogic.client.FailedRequestException: Local message: /config/query write failed: Internal Server Error. Server Message: XDMP-NONMIXEDCOMPLEXCONT: fn:data(<properties xmlns="http://marklogic.com/rest-api"><content-versions>...</content-versions>...</properties>) -- Node has complex type with non-mixed complex content . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2873)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2730)
        at com.marklogic.client.impl.QueryOptionsManagerImpl.writeOptions(QueryOptionsManagerImpl.java:158)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installQueryOptions$3(DefaultModulesLoader.java:464)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:501)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

BUILD SUCCESSFUL in 3s
2 actionable tasks: 2 executed
```

Removing the file causes the error to go away. That file is based on the Management API's [/v1/config/properties endpoint](http://docs.marklogic.com/REST/GET/v1/config/properties). Where should it go in an ml-gradle project?

**Comment by rjrudin** [comment]
It's expected to be at src/main/ml-modules/rest-properties.json. I'll include a fix in 3.6.0 for copying that file - is it always named properties.xml?

**Comment by dmcassel** [comment]
Yes, in Roxy projects it's always properties.xml.

**Comment by rjrudin** [comment]
So the rule should be - everything under "rest-api/config" should be an options file, except "properties.xml", correct?

**Comment by dmcassel** [comment]
Here are the paths a Roxy project typically has:

- rest-api/config/properties.xml
- rest-api/config/options/all.xml

Other options configs would also be under the options directory.

**Comment by rjrudin** [comment]
Okay I think "options" is buggy too then - I thought the options files were directly under "config". I'll modify the "migrate Roxy files" task to look under "config/options" instead too.
