### ISSUE TITLE
Errors after switching REST API Server from digest to basic authentication.

### ISSUE THREAD

**Issue by darrelcox** [marklogic-community/ml-gradle#334]
My REST API Server was originally created with digest authentication but was immediately changed to basic via the Admin Console. I have also updated the rest-api-server.json and gradle.properties to specify basic authentication. 

Now when I do a ReloadModules : **gradle -i mlReloadModules** 

I get these errors : 

**401 Unauthorized**
**previous digest authentication with same nonce failed, returning null**

```
> Task :mlClearModulesDatabase
Task ':mlClearModulesDatabase' is not up-to-date because:
  Task has not declared any outputs.
Clearing modules database
Invoking operation clear-database on database liveSearch-modules
Sending JSON POST request as user '' to path: /manage/v2/databases/liveSearch-modules
Logging HTTP response body to assist with debugging: {"errorResponse":   {"statusCode":401,
   "status":"Unauthorized",
   "message":"401 Unauthorized"
  }
}
Unable to clear database; cause: 401 Unauthorized
Finished clearing modules database

:mlClearModulesDatabase (Thread[Task worker for ':',5,main]) completed. Took 0.02 secs.
:mlPrepareRestApiDependencies (Thread[Task worker for ':',5,main]) started.

> Task :mlPrepareRestApiDependencies
Task ':mlPrepareRestApiDependencies' is not up-to-date because:
  Task has not declared any outputs.

:mlPrepareRestApiDependencies (Thread[Task worker for ':',5,main]) completed. Took 0.001 secs.
:mlLoadModules (Thread[Task worker for ':',5,main]) started.
previous digest authentication with same nonce failed, returning null
Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4317)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3381)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:48)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:74)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
Writing resource services source for entity
Error caught while loading modules, cause: Local message: config/resources write failed: Unauthorized. Server Message: Unauthorized
com.marklogic.client.FailedRequestException: Local message: config/resources write failed: Unauthorized. Server Message: Unauthorized
        at com.marklogic.client.impl.OkHttpServices.putPostValueImpl(OkHttpServices.java:2873)
        at com.marklogic.client.impl.OkHttpServices.putValue(OkHttpServices.java:2740)
        at com.marklogic.client.impl.ResourceExtensionsImpl.writeServices(ResourceExtensionsImpl.java:206)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$installService$1(DefaultModulesLoader.java:408)
        at com.marklogic.client.ext.modulesloader.impl.DefaultModulesLoader.lambda$executeTask$5(DefaultModulesLoader.java:501)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)

```

I'm hoping to do this without requiring a server restart.

**Comment by rjrudin** [comment]
What do you have in gradle.properties? I ask because it looks like mlManageUsername might be setting to nothing based on this line of logging:

    Sending JSON POST request as user '' to path: /manage/v2/databases/liveSearch-modules

**Comment by darrelcox** [comment]
The mlManageUsername properties is not being directly set in the gradle.properties file(s) so it defaults to mlUsername which is currently being set to "mlUsername=", which means it is null. **After setting mlUsername and mlPassword everything seems to work as expected**. Thanks Rob.
