### ISSUE TITLE
Run gradle mlDeploy via ssl fails when writing modules and properties

### ISSUE THREAD

**Issue by peetkes** [marklogic-community/ml-gradle#338]
Hi,
I just tries deploying my test app on a dev environment that has ssl enabled on 8000, 8001 and 8002
When it tries to load the modules it will fail with the following:

.....
Executing command [com.marklogic.appdeployer.command.flexrep.DeployFlexrepCommand] with sort order [300]
Flexrep path not configured, so not attempting to find any Flexrep resources to deploy
Finished executing command [com.marklogic.appdeployer.command.flexrep.DeployFlexrepCommand]

Executing command [com.marklogic.appdeployer.command.schemas.LoadSchemasCommand] with sort order [350]
Loading schemas from path: src/main/ml-schemas
Initializing ExecutorService
Path does not exist, so not reading files from it: src/main/ml-schemas
Finished loading schemas from: src/main/ml-schemas
Releasing connection
Finished executing command [com.marklogic.appdeployer.command.schemas.LoadSchemasCommand]

Executing command [com.marklogic.appdeployer.command.clusters.ModifyLocalClusterCommand] with sort order [350]
No resource directory found at: C:\Users\XXXXX\Projects\test\src\main\ml-config\clusters
Finished executing command [com.marklogic.appdeployer.command.clusters.ModifyLocalClusterCommand]

Executing command [com.marklogic.appdeployer.command.modules.LoadModulesCommand] with sort order [400]
Initializing new instance of ModulesLoader
Loading asset modules from dir: src/main/ml-modules
Initializing ExecutorService
Initializing ExecutorService
Writing 1 files
Writing: /lib/exif-consts.xqy
Shutting down ExecutorService
Shutting down ExecutorService

Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.MarkLogicIOException: java.io.IOException: Unexpected response code for CONNECT: 502
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:697)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
        at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4052)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3353)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:48)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 502
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:389)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:211)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:152)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
        ... 15 more

> Task :mlDeployApp FAILED
Loading all non-asset modules from dir: src/main/ml-modules
Initializing ExecutorService
Writing REST server configuration
Default document read transform: null
Transform all documents on read: false
Validate query options: true
Validate queries: true
Output debugging: false
Writing server configuration
Releasing connection
:mlDeployApp (Thread[Daemon worker Thread 10,5,main]) completed. Took 2.924 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mlDeployApp'.
> Local message: config/properties write failed: Bad Gateway. Server Message: Server (not a REST instance?) did not respond with an expected REST Error message.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
4 actionable tasks: 4 executed

C:\Users\XXXXX\Projects\test>

my properties file looks like this:
mlHost=XXXXXX
mlManageSimpleSsl=true
mlManageScheme=https

mlAdminSimpleSsl=true
mlAdminScheme=https

mlAppServicesSimpleSsl=true
mlAppServicesScheme=https

**Comment by rjrudin** [comment]
@peetkes What version of ML are you on? If not 9.0-4, can you try that?

Also, are you able to share the certificate template that you're using for port 8000?

**Comment by peetkes** [comment]
This was my bad... forgot to add the ssl switch for the application port
