### ISSUE TITLE
Error with mlLoadModules

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/ml-gradle#406]
We're using external security, so the authentication on our REST server is:

- authentication: basic
- internal security: false
- external security: Active Directory config

I'm trying to run `gradle mlLoadModules` , but getting an error. 

```
16:37:06.059 [ERROR] [system.err] Exception in thread "ThreadPoolTaskExecutor-1" java.lang.IllegalArgumentException: unsupported auth scheme: [Basic realm=public]
16:37:06.059 [ERROR] [system.err]       at com.burgstaller.okhttp.digest.DigestAuthenticator.findDigestHeader(DigestAuthenticator.java:198)
16:37:06.060 [ERROR] [system.err]       at com.burgstaller.okhttp.digest.DigestAuthenticator.authenticate(DigestAuthenticator.java:163)
16:37:06.060 [ERROR] [system.err]       at com.burgstaller.okhttp.CachingAuthenticatorDecorator.authenticate(CachingAuthenticatorDecorator.java:30)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:289)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:157)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
16:37:06.060 [ERROR] [system.err]       at com.burgstaller.okhttp.AuthenticationCacheInterceptor.intercept(AuthenticationCacheInterceptor.java:45)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
16:37:06.060 [ERROR] [system.err]       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
16:37:06.061 [ERROR] [system.err]       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
16:37:06.061 [ERROR] [system.err]       at okhttp3.RealCall.execute(RealCall.java:77)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:695)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.OkHttpServices.sendRequestOnce(OkHttpServices.java:690)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.OkHttpServices.doPost(OkHttpServices.java:4052)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3353)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3461)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
16:37:06.061 [ERROR] [system.err]       at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
16:37:06.062 [ERROR] [system.err]       at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
16:37:06.062 [ERROR] [system.err]       at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:48)
16:37:06.062 [ERROR] [system.err]       at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:80)
16:37:06.062 [ERROR] [system.err]       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:37:06.062 [ERROR] [system.err]       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
16:37:06.062 [ERROR] [system.err]       at java.lang.Thread.run(Thread.java:748)
```

Basic auth seems to go along with external security. We recently upgraded from ml-gradle 2.7.0 to 3.9.0, so there's a good chance that's related. Is this likely a config change that we need to make or is there a bug? 

[load.log](https://github.com/marklogic-community/ml-gradle/files/2601709/load.log)

**Comment by rjrudin** [comment]
I'm not sure how to construct a DatabaseClient when using external security. If it's possible, it can be done via the sample at https://github.com/marklogic-community/ml-gradle/wiki/Debugging-module-loading#debugging-module-loading-without-involving-ml-gradle - make sure to use the port of your app server that uses external security.

If you're able to get that script working, then you should be able to configure ml-gradle to construct the appropriate DatabaseClient using the properties at https://github.com/marklogic-community/ml-gradle/wiki/Property-reference#rest-api-server-connection-properties

**Comment by dmcassel** [comment]
I added the following to my `build.gradle`:

```
mlLoadModules {
    doFirst {
        def context = new com.marklogic.client.DatabaseClientFactory.BasicAuthContext(mlUsername, mlPassword)
        def client = com.marklogic.client.DatabaseClientFactory.newClient(mlHost, 8060, "my-modules", context)

        try {
            client.newDocumentManager().write("/test/module.xqy", new com.marklogic.client.io.StringHandle("<hello>world</hello>"))
        } finally {
            client.release()
        }
    }
}
```

That successfully writes `/test/module.xqy` to the modules database. It then goes on to fail in the same way as before for the rest of the modules. That makes sense, as I'm creating local variables. However, I haven't figured out how to get the `mlLoadModules` task to use that info. Based on walking through the ml-gradle and ml-app-deployer code, I thought this would help, but I see no evidence that it's being used:

```
ext {
    mlCommandContext {
        restAuthentication = "$mlRestAuthentication"
        mlRestPort=8060
        mlRestExternalName="MyAD"
    }
}
```

Am I on the right track with trying to set things with `mlCommandContext`? Any suggestions on what properties I should be setting there?

**Comment by rjrudin** [comment]
Do "mlAppConfig" instead of "mlCommandContext"... but note that non-REST modules are loaded via 8000, while REST modules have to be loaded via 8060. Are both using external security, or only 8060?

If only 8060 is, try this in gradle.properties to force 8060 to be used for both REST modules and non-REST modules:

```
mlRestAuthentication=basic
mlAppServicesPort=8060
mlRestPort=8060
mlUsername=changeme
mlPassword=changeme
```

**Comment by dmcassel** [comment]
It's working now. Your note about modules being loaded on 8000 vs 8060 made the difference. I kept `mlAppServicesPort` as 8000 and added `mlUsername` with an internal-security user (admin), and set `mlRestAdminUsername` to an externally authenticated user. Not quite ideal, but it works. I'll play with it a bit more and see whether I can get everything using the external user, but at least this removes the blocker. Thanks, Rob!
