### ISSUE TITLE
Schema forest not connected to the schema database

### ISSUE THREAD

**Issue by prestonmcgowan** [marklogic-community/ml-gradle#468]
I have a schema database configured. 
ml-gradle looks to be creating the schema forest and the database, the forest is never added to the database however so the mlDeploy is failing.

ml-gradle: 3.13.0 and 3.14.0.
MarkLogic 9.0-9
MacOS 10.14

## gradle mlDeploy
```
Exception in thread "ThreadPoolTaskExecutor-1" com.marklogic.client.FailedRequestException: Local message: failed to apply resource at documents: Internal Server Error. Server Message: XDMP-NOFORESTS: Database geo-data-services-schemas contains no forests . See the MarkLogic server error log for further detail.
        at com.marklogic.client.impl.OkHttpServices.checkStatus(OkHttpServices.java:4395)
        at com.marklogic.client.impl.OkHttpServices.postResource(OkHttpServices.java:3467)
        at com.marklogic.client.impl.OkHttpServices.postBulkDocuments(OkHttpServices.java:3547)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:614)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:606)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.impl.DocumentManagerImpl.write(DocumentManagerImpl.java:590)
        at com.marklogic.client.impl.GenericDocumentImpl.write(GenericDocumentImpl.java:23)
        at com.marklogic.client.ext.batch.DefaultBatchHandler.handleBatch(DefaultBatchHandler.java:54)
        at com.marklogic.client.ext.batch.RestBatchWriter$1.run(RestBatchWriter.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## MarkLogic ErrorLog
```
$ tail -n 500 8000_ErrorLog.txt
2019-05-31 13:24:51.204 Info: Status 500: XDMP-NOFORESTS: Database geo-data-services-schemas contains no forests
```

**Comment by prestonmcgowan** [comment]
I was able to work around this issue by connecting the schema database's forest by hand, and re-executing mlDeploy

**Comment by rjrudin** [comment]
Can you describe how to reproduce this? Never seen something like this before.

**Comment by prestonmcgowan** [comment]
I have been able to recreate this issue with and without mlBundle.

No mlBundle: gradle -PenvironmentName=test mlDeploy
https://github.com/marklogic-community/marklogic-geo-data-services/blob/issues/4/build.gradle

With mlBundle: gradle mlDeploy
https://github.com/marklogic-community/marklogic-geo-data-services/blob/issues/4/examples/sample-project/build.gradle

**Comment by rjrudin** [comment]
I wasn't able to reproduce this on either the root project (once the properties plugin was applied) nor on the sample project. Here's the relevant logging from deploying the sample project, and I verified in the admin UI that the forest was created and properly attached:

```
Checking for existence of resource: sample-project-schemas
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Creating database: sample-project-schemas
Sending JSON POST request as user 'admin' to path: /manage/v2/databases
Created database: sample-project-schemas
Sending XML GET request as user 'admin' to path: /manage/v2/hosts
Only creating forests on the first host: macpro-5022.home
Checking for existence of resource: sample-project-schemas
Sending XML GET request as user 'admin' to path: /manage/v2/databases
Sending XML GET request as user 'admin' to path: /manage/v2/databases/sample-project-schemas/properties
Checking for existence of resource: sample-project-schemas-1
Sending XML GET request as user 'admin' to path: /manage/v2/forests
Creating forest: sample-project-schemas-1
Sending JSON POST request as user 'admin' to path: /manage/v2/forests
Created forest: sample-project-schemas-1
```

**Comment by rjrudin** [comment]
I believe this was fixed as well by applying the properties plugin?
