### ISSUE TITLE
mlcp-project error 

### ISSUE THREAD

**Issue by haritrichy** [marklogic-community/ml-gradle#486]
I receive the following error while trying to run mlcp-project with ".\gradlew.bat importSemicolonDelimitedText". Can anyone help? Thanks

2019-07-07 12:12:28 ERROR Shell:373 - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
        at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:355)
        at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:370)
        at org.apache.hadoop.util.Shell.<clinit>(Shell.java:363)
        at org.apache.hadoop.util.GenericOptionsParser.preProcessForWindows(GenericOptionsParser.java:438)
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:484)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
        at com.marklogic.contentpump.ContentPump.runCommand(ContentPump.java:111)
        at com.marklogic.contentpump.ContentPump.main(ContentPump.java:74)
2019-07-07 12:12:28 INFO  LocalJobRunner:498 - Content type: XML
2019-07-07 12:12:29 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2019-07-07 12:12:29 INFO  ContentPump:227 - Job name: local_1296082288_1
2019-07-07 12:12:29 INFO  FileAndDirectoryInputFormat:217 - Total input paths to process : 1
2019-07-07 12:12:29 ERROR LocalJobRunner:159 - Error checking output specification:
2019-07-07 12:12:29 ERROR LocalJobRunner:160 - java.io.IOException: com.marklogic.xcc.exceptions.XQueryException: XDMP-NOSUCHDB: No such database mlcp-project-content
 [Session: user=admin, cb=mlcp-project-content [ContentSource: user=admin, cb=mlcp-project-content [provider: address=localhost/127.0.0.1:8000, pool=1/64]]]
 [Client: XCC/9.0-7, Server: XDBC/10.0-1]
:importSemicolonDelimitedText FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':importSemicolonDelimitedText'.

**Comment by haritrichy** [comment]
I found the solution [here](https://github.com/marklogic-community/ml-gradle/wiki/MarkLogic-Content-Pump-(mlcp)-and-Gradle#suppressing-hadoop-binary-messages-on-windows)
