### ISSUE TITLE
Update jsDoc example to use latest versions

### ISSUE THREAD

**Issue by brent-hartwig** [marklogic-community/ml-gradle#564]
**Describe the bug**
The default Node version used by `examples/jsdoc-project` (as is) is 5.5.0, which leads to compliation errors that prevent `generateJsDoc` from completing successfully.

**To Reproduce**
1. Clone the repo
2. Run `gradle generateJsDoc` (output follows)

```
$ gradle generateJsDoc

> Task :downloadJSDoc
npm WARN engine catharsis@0.8.11: wanted: {"node":">= 8"} (current: {"node":"5.5.0","npm":"3.3.12"})
C:\workspaces\ws-ml-community\ml-gradle-derms\examples\jsdoc-project
└─┬ jsdoc@3.5.5
  ├── babylon@7.0.0-beta.19
  ├── bluebird@3.5.5
  ├─┬ catharsis@0.8.11
  │ └── lodash@4.17.19
  ├── escape-string-regexp@1.0.5
  ├─┬ js2xmlparser@3.0.0
  │ └── xmlcreate@1.0.2
  ├─┬ klaw@2.0.0
  │ └── graceful-fs@4.2.4
  ├── marked@0.3.19
  ├─┬ mkdirp@0.5.5
npm  │ └── minimist@1.2.5
  ├── requizzle@0.2.3
  ├── strip-json-comments@2.0.1
  ├── taffydb@2.6.2
 WARN ENOENT ENOENT: no such file or directory, open 'C:\workspaces\ws-ml-community\ml-gradle-derms\examples\jsdoc-project\package.json'
npm WARN EPACKAGEJSON jsdoc-project No description
npm WARN EPACKAGEJSON jsdoc-project No repository field.
  └── underscore@1.8.3

npm WARN EPACKAGEJSON jsdoc-project No README data
npm WARN EPACKAGEJSON jsdoc-project No license field.

> Task :generateJsDoc FAILED
C:\workspaces\ws-ml-community\ml-gradle-derms\examples\jsdoc-project\node_modules\requizzle\index.js:11
    let instance;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at C:\workspaces\ws-ml-community\ml-gradle-derms\examples\jsdoc-project\node_modules\jsdoc\jsdoc.js:20:15
    at Object.<anonymous> (C:\workspaces\ws-ml-community\ml-gradle-derms\examples\jsdoc-project\node_modules\jsdoc\jsdoc.js:37:3)
    at Module._compile (module.js:413:34)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateJsDoc'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34s
3 actionable tasks: 3 executed
```

**Expected behavior**
Directions on what additional environment set up is required before expecting this task to work, or an updated build.gradle file that takes care of this for the user.  If not completely specified in build.gradle, perhaps we can include a combination of versions known to work: Java, Gradle, ml-gradle, Node, and Liferay (node and app.jsdoc).

**Comment by rjrudin** [comment]
Want to submit a PR to upgrade it?

**Comment by brent-hartwig** [comment]
On its way :)

**Comment by brent-hartwig** [comment]
@rjrudin, would you prefer a separate ticket to add support for MJS?

**Comment by brent-hartwig** [comment]
May I have permission to create a remote branch?  See error message at end.

```
bhartwig MINGW64 /c/workspaces/ws-ml-community
$ git clone https://github.com/marklogic-community/ml-gradle.git
Cloning into 'ml-gradle'...
remote: Enumerating objects: 103, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 8057 (delta 36), reused 65 (delta 8), pack-reused 7954
Receiving objects: 100% (8057/8057), 1.51 MiB | 8.00 MiB/s, done.
Resolving deltas: 100% (3559/3559), done.
Checking out files: 100% (762/762), done.

bhartwig MINGW64 /c/workspaces/ws-ml-community
$ cd ml-gradle

bhartwig MINGW64 /c/workspaces/ws-ml-community/ml-gradle (master)
$ git checkout dev
Switched to a new branch 'dev'
Branch 'dev' set up to track remote branch 'dev' from 'origin'.

bhartwig MINGW64 /c/workspaces/ws-ml-community/ml-gradle (dev)
$ git checkout -b issue-564
Switched to a new branch 'issue-564'

bhartwig MINGW64 /c/workspaces/ws-ml-community/ml-gradle (issue-564)
$ git push -u origin issue-564
remote: Permission to marklogic-community/ml-gradle.git denied to brent-hartwig.
fatal: unable to access 'https://github.com/marklogic-community/ml-gradle.git/': The requested URL returned error: 403
```

**Comment by rjrudin** [comment]
Just fork ml-gradle and create a remote branch in your fork - you can submit the PR from that branch. That's the standard github practice.

**Comment by brent-hartwig** [comment]
PR: https://github.com/marklogic-community/ml-gradle/pull/565
