### ISSUE TITLE
java.nio.file.NoSuchFileException when running mlUnitTest

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/ml-gradle#599]
I have a few really basic example unit tests (`assertTrue(true)` and such), which run fine with ml-gradle 3.17.1, but I the a java.nio.file.NoSuchFileException exception using ml-gradle 4.1.1. No clue why. The error looks very similar to that of marklogic-community/marklogic-unit-test#75, but there are no nested tests, only very simple ones..

**Comment by grtjn** [comment]
The stacktrace doesn't tell a lot, except that it is using a relative path, though not telling from which folder..

**Comment by grtjn** [comment]
```
Caused by: java.nio.file.NoSuchFileException: build\test-results\marklogic-unit-test\TEST-avg.xml
        at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:80)
        at org.springframework.util.FileCopyUtils$copy.call(Unknown Source)
        at com.marklogic.gradle.task.test.UnitTestTask.runUnitTests(UnitTestTask.groovy:94)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        ... 91 more
```

**Comment by rjrudin** [comment]
I can't reproduce this, but my guess is that the call to "resultsDir.mkdirs()" is failing silently. And then when mlUnitTest tries to write a file to that directory, we get the error. 

Given that something is going to fail here if resultsDir cannot be created, it seems better for an exception to be thrown if mkdirs() does not succeed. So that's the path I'm going to take.

**Comment by rjrudin** [comment]
Will include a presumed fix in 4.3.0. Most of the logic in UnitTestTask really should move into a non-Gradle-specific class in marklogic-unit-test, which will make testing it easier. 

@grtjn Please reopen this if it's still an issue once 4.3.0 is out.

**Comment by grtjn** [comment]
+1 on moving part or all of this code to ml-unit-test ;)

**Comment by grtjn** [comment]
@rjrudin we moved over from straight ml-gradle to DHF, so not always clear which ml-gradle is used, nor whether DHF is meddling with ml-gradle tasks. Any command, channel or doc I can watch to know if DHF is using ml-gradle 4.3.0?

**Comment by rjrudin** [comment]
@grtjn Sorry for the delay - run "./gradlew buildEnvironment", which shows all the plugins applied and their dependencies.
